title: <p align="center"> Siddharth Sharma </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/siddharth-sharma-317843b8/">LinkedIn</a> |
  <a href="https://github.com/SiddharthSharma15">GitHub</a>
  
  <br>   
  I'm working as QA Manager and looking to make transition to QA Profile. I am keen to learn and implement solutions for Data Science, Big Data, Spark, Machine learning & NLP related problems.
  My toal working expereindce is 11 + years.
  <br>
  </p>

theme: jekyll-theme-minimal
